
version: '3.9'

services:
  backend:
    build: ../backend/backend_api
    ports:
      - "8000:8000"
    env_file:
      - ../backend/backend_api/.env
    volumes:
      - ../backend:/app
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: ../backend/backend_api
    command: celery -A app.tasks.celery_app.celery worker --loglevel=info
    volumes:
      - ../backend:/app
    depends_on:
      - redis
    env_file:
      - ../backend/backend_api/.env

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
    env_file:
      - ../frontend/.env
    command: npm run dev
