services:
  - type: web
    name: fitinty-backend
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /docs
    envVars:
      - key: PORT
        value: 8000

  - type: worker
    name: fitinty-celery-worker
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: fitinty-redis
          property: connectionString

  - type: redis
    name: fitinty-redis
    plan: free
